[package]
name = "worlds"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies.dorp]
git = "https://github.com/yeliknewo/rs-dorp.git"
version = "*"

[dependencies]
rand = "0.3.14"
